export const travels = [
  {
    adventure: 'West Coast Trail',
    province: 'British Columbia',
    description: "Arguably Canada's most famous hiking trail.",
    start: '02.04.21',
    duration: 7,
    price: 799,
    difficulty: 'easy',
  },
  {
    adventure: 'Killarney Park',
    province: 'Ontario',
    description: "Ontario's crown jewel of provincial parks.",
    start: '07.09.21',
    duration: 3,
    price: 299,
    difficulty: 'easy',
  },
  {
    adventure: 'Plain of Six Glaciers Trail',
    province: 'Alberta',
    description: 'A breathtaking way to take in the Rocky Mountains.',
    start: '10.06.21',
    duration: 10,
    price: 999,
    difficulty: 'moderate',
  },
  {
    adventure: 'Cape Breton National Highlands Park',
    province: 'Nova Scotia',
    description: 'Intimately explore stunning canyon and ocean views.',
    start: '03.07.21',
    duration: 5,
    price: 599,
    difficulty: 'easy',
  },
  {
    adventure: 'Sunshine to Mt. Assiniboine',
    province: 'Alberta',
    description: 'Considered the best multi-day trek in the Canadian Rockies.',
    start: '15.05.21',
    duration: 7,
    price: 899,
    difficulty: 'challenging',
  },
  {
    adventure: 'Bruce Trail',
    province: 'Ontario',
    description:
      'A protected respite in the most populous part of the country.',
    start: '07.06.21',
    duration: 4,
    price: 399,
    difficulty: 'moderate',
  },
  {
    adventure: 'Fundy Trail',
    province: 'New Brunswick',
    description:
      'Tidal action created a dramatic landscape of cliffs and sea stacks.',
    start: '01.09.21',
    duration: 10,
    price: 1099,
    difficulty: 'moderate',
  },
  {
    adventure: 'East Coast Trail',
    province: 'Newfoundland & Labrador',
    description:
      'The beauty of the landscape is a fitting backdrop to the charm of the people.',
    start: '15.03.21',
    duration: 4,
    price: 499,
    difficulty: 'easy',
  },
  {
    adventure: 'Gaspesié National Park',
    province: 'Quebec',
    description: 'Some very beautiful scenes of mountain meeting water.',
    start: '01.03.21',
    duration: 2,
    price: 199,
    difficulty: 'moderate',
  },
  {
    adventure: 'Canol Heritage Trail',
    province: 'Northwest Territories',
    description:
      'A thoroughly remote trail, recommended for experienced wilderness hikers.',
    start: '20.08.21',
    duration: 20,
    price: 2199,
    difficulty: 'challenging',
  },
];
